/**
 * Type declarations for supabase-service.js
 * This allows TypeScript to import the JS module without errors
 */

export function getClient(): unknown;
export function getAllKunder(): Promise<unknown[]>;
export function getKundeById(id: number): Promise<unknown>;
export function createKunde(kunde: unknown): Promise<unknown>;
export function updateKunde(id: number, kunde: unknown): Promise<unknown>;
export function deleteKunde(id: number): Promise<{ success: boolean }>;
export function getKunderByOmrade(omrade: string): Promise<unknown[]>;
export function getKontrollVarsler(dagerFrem?: number): Promise<unknown[]>;
export function getOmrader(organizationId?: number | null): Promise<unknown[]>;
export function bulkImportKunder(kunder: unknown[]): Promise<{ imported: number; errors: unknown[]; total: number }>;
export function getAllKunderWithServices(organizationId?: number | null): Promise<unknown[]>;
export function getKundeByIdWithServices(id: number, organizationId?: number | null): Promise<unknown>;
export function getKontrollVarslerDynamic(dagerFrem?: number, organizationId?: number | null): Promise<unknown[]>;
export function getAllRuter(): Promise<unknown[]>;
export function getRuteById(id: number): Promise<unknown>;
export function createRute(ruteData: unknown): Promise<unknown>;
export function updateRute(id: number, ruteData: unknown): Promise<unknown>;
export function deleteRute(id: number): Promise<{ success: boolean }>;
export function completeRute(id: number, dato?: string): Promise<{ success: boolean; oppdaterte_kunder: number }>;
export function getEmailInnstillinger(kundeId: number): Promise<unknown>;
export function updateEmailInnstillinger(kundeId: number, settings: unknown): Promise<{ success: boolean }>;
export function getEmailHistorikk(organizationId: number, kundeId?: number | null, limit?: number): Promise<unknown[]>;
export function getEmailStats(organizationId: number): Promise<{ pending: number; sent: number; failed: number }>;
export function getUpcomingEmails(organizationId: number, firstReminderDays: number): Promise<unknown[]>;
export function insertEmailVarsel(varsel: unknown): Promise<unknown>;
export function logEmailReminder(kundeId: number, daysUntil: number, status: string): Promise<unknown>;
export function getKlientByEpost(epost: string): Promise<unknown>;
export function getKlientById(id: number): Promise<unknown>;
export function getAllKlienter(): Promise<unknown[]>;
export function createKlient(klient: unknown): Promise<unknown>;
export function updateKlientLastLogin(id: number): Promise<void>;
export function getBrukerByEpost(epost: string): Promise<unknown>;
export function getBrukerById(id: number): Promise<unknown>;
export function updateBrukerLastLogin(id: number): Promise<void>;
export function storeRefreshToken(tokenHash: string, userId: number, userType: string, deviceInfo: string, ipAddress: string, expiresAt: string): Promise<unknown>;
export function getRefreshTokenRecord(tokenHash: string): Promise<unknown>;
export function revokeRefreshToken(tokenHash: string, replacedBy?: string | null): Promise<boolean>;
export function revokeAllUserRefreshTokens(userId: number, userType: string): Promise<number>;
export function getAllAvtaler(): Promise<unknown[]>;
export function getAvtalerByDateRange(startDate: string, endDate: string): Promise<unknown[]>;
export function getAvtaleById(id: number): Promise<unknown>;
export function createAvtale(avtale: unknown): Promise<unknown>;
export function updateAvtale(id: number, avtale: unknown): Promise<unknown>;
export function deleteAvtale(id: number): Promise<{ success: boolean }>;
export function completeAvtale(id: number, completionData: unknown): Promise<{ success: boolean }>;
export function getKontaktloggByKunde(kundeId: number, organizationId: number): Promise<unknown[]>;
export function createKontaktlogg(kontakt: unknown): Promise<unknown>;
export function deleteKontaktlogg(id: number): Promise<{ success: boolean }>;
export function logLogin(epost: string, brukerNavn: string, brukerType: string, status: string, ipAdresse: string, userAgent: string, feilMelding?: string | null): Promise<void>;
export function getLoginLogg(limit?: number, offset?: number): Promise<unknown[]>;
export function getLoginLoggCount(): Promise<number>;
export function getLoginStats(): Promise<{ total: number; vellykket: number; feilet: number; siste24t: number; siste7d: number }>;
export function getOrganizationById(id: number): Promise<unknown>;
export function getOrganizationBySlug(slug: string): Promise<unknown>;
export function getAllOrganizations(): Promise<unknown[]>;
export function createOrganization(org: unknown): Promise<unknown>;
export function updateOrganization(id: number, org: unknown): Promise<unknown>;
export function getAllKunderByTenant(organizationId: number): Promise<unknown[]>;
export function getKundeByIdAndTenant(id: number, organizationId: number): Promise<unknown>;
export function getRuterByTenant(organizationId: number): Promise<unknown[]>;
export function getAvtalerByTenant(organizationId: number, startDate?: string, endDate?: string): Promise<unknown[]>;
export function getAllIndustryTemplates(): Promise<unknown[]>;
export function getIndustryTemplateById(id: number): Promise<unknown>;
export function getIndustryTemplateBySlug(slug: string): Promise<unknown>;
export function getServiceTypesByTemplate(templateId: number): Promise<unknown[]>;
export function getIntervalsByTemplate(templateId: number): Promise<unknown[]>;
export function getFullIndustryConfig(templateIdOrSlug: number | string): Promise<unknown>;
export function getCustomerServices(kundeId: number): Promise<unknown[]>;
export function upsertCustomerService(kundeId: number, serviceTypeId: number, serviceData: unknown): Promise<unknown>;
export function deleteCustomerService(kundeId: number, serviceTypeId: number): Promise<boolean>;
export function getCustomerServicesWithUpcoming(days?: number, organizationId?: number | null): Promise<unknown[]>;
export function completeCustomerService(kundeId: number, serviceTypeId: number, completionDate?: string): Promise<unknown>;
export function bulkCompleteServices(customerIds: number[], serviceTypeSlug: string, completionDate?: string): Promise<{ success: boolean; updatedCount: number }>;
export function getServiceTypeBySlug(slug: string): Promise<unknown>;
export function getAllServiceTypes(templateId?: number | null): Promise<unknown[]>;
export function createOrUpdateCustomerServices(kundeId: number, servicesData: unknown[]): Promise<unknown[]>;
export function deactivateCustomerServices(kundeId: number, activeServiceTypeIds?: number[]): Promise<void>;
